name: Webdriverio tests

on:
  push:
    branches: ["main", "webdriverio"]
  pull_request:
    branches: ["main", "webdriverio"]
  workflow_dispatch:

jobs:
  test:
    strategy:
      fail-fast: false
      matrix:
        os: [macos-13, ubuntu-latest]
        node-version: [18.x, 20.x]
    runs-on: ${{ matrix.os }}
        # See supported Node.js release schedule at https://nodejs.org/en/about/releases/
    steps:
    - name: Checkout
      uses: actions/checkout@v4
      with:
        submodules: true
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v4
      with:
        node-version: ${{ matrix.node-version }}
        cache: 'npm'
    - run: npm ci
    - run: npm run build --if-present
    - run: npm run serve-and-test
