# This is a basic workflow to help you get started with Actions

name: deploy via ssh
on:
  push:
    branches:
      - master
jobs:
  deploy:
    name: deploy
    runs-on: ubuntu-latest
    steps:
    - name: executing remote ssh commands
      uses: appleboy/ssh-action@master
      with:
        host: ${{ secrets.HOST }}
        username: ${{ secrets.USERNAME }}
        key: ${{ secrets.KEY }}
        passphrase: ${{ secrets.PASSPHRASE }}
        port: ${{ secrets.PORT }}
        use_insecure_cipher: true
        debug: true
        script: |
          cd ~/contributoragreements.org/ca-cla-chooser
          git pull

