name: Surge PR Preview

on:
  pull_request_target:
    types: [opened, reopened, synchronize, closed]

jobs:
  preview:
    runs-on: ubuntu-latest
    permissions:
      pull-requests: write # allow surge-preview to create/update PR comments
    steps:
      - uses: actions/checkout@v4
        with:
          ref: ${{ github.event.pull_request.head.sha }}
      - name: Generate config files
        run: |
          git rev-parse --short HEAD > version.log
          echo '{"serviceUrl":"https://contributoragreements.org","urlShortener":"https://contributoragreements.org/u2s"}' > js/config.json
      - uses: step21/surge-preview-fork@first-release
        id: preview_step
        with:
          surge_token: ${{ secrets.SURGE_TOKEN }}
          github_token: ${{ secrets.GITHUB_TOKEN }}
          dist: .
          build: npm ci
      - name: Get the preview_url
        run: echo "url => ${{ steps.preview_step.outputs.preview_url }}"
